# Generated by Django 5.2.4 on 2025-07-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "칼럼", "verbose_name_plural": "칼럼"},
        ),
        migrations.AlterModelOptions(
            name="cuisinetype",
            options={"verbose_name": "음식 종류", "verbose_name_plural": "음식 종류"},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"verbose_name": "레스토랑", "verbose_name_plural": "레스토랑"},
        ),
        migrations.AlterModelOptions(
            name="restaurantcategory",
            options={
                "verbose_name": "가게 카테고리",
                "verbose_name_plural": "가게 카테고리",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurantimage",
            options={
                "verbose_name": "가게 이미지",
                "verbose_name_plural": "가게 이미지",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurantmenu",
            options={"verbose_name": "가게 메뉴", "verbose_name_plural": "가게 메뉴"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "리뷰",
                "verbose_name_plural": "리뷰",
            },
        ),
        migrations.RenameField(
            model_name="restaurantcategory",
            old_name="cuisineType",
            new_name="cuisine_type",
        ),
        migrations.AlterField(
            model_name="article",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="article"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="영업 종료 시간"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="feature",
            field=models.CharField(max_length=255, verbose_name="특징"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="폐업 여부"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="E.164 포맷",
                max_length=16,
                null=True,
                verbose_name="전화번호",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default="0.0", max_digits=3, verbose_name="평점"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="영업 시작 시간"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="생성일"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="review-profile",
                verbose_name="프로필 이미지",
            ),
        ),
    ]
